# Stage 1: Build the Go application
FROM golang:alpine as builder
RUN apk add --no-cache git

WORKDIR /go/src/app

# Install reflex
RUN go install github.com/cespare/reflex@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o run .

# Stage 2: Create a small image with only the necessary runtime dependencies
FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /go/src/app/run .
COPY --from=builder /go/bin/reflex /usr/local/bin/reflex

CMD ["./run"]
