version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodbDATA:/data/db
    networks:
      - application-network

  app:
    build:
      context: ./
      dockerfile: infrastructure/Docker/Dockerfile.dev
    image: app
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongodb
    networks:
      - application-network
    command: reflex -r '\.go$' -s -- go run ./cmd/server/main.go

networks:
  application-network:
    driver: bridge

volumes:
  mongodbDATA:
