name: Auto Merge for Docs

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR opened, updated, or reopened.
    branches: [*]  # Apply to all branches.
    paths:
      - '**/*.md'  # Trigger only for changes in markdown files (docs).

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up GitHub CLI
      uses: cli/cli@v2
      with:
        version: '2.x'

    - name: Check for successful status checks
      run: |
        pr_number=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)
        status=$(gh pr view "$pr_number" --json checkSuites -q ".checkSuites.state")
        
        if [ "$status" != "SUCCESS" ]; then
          echo "Required checks have not passed. Exiting."
          exit 1
        fi

    - name: Check if the PR is only documentation changes
      run: |
        pr_files=$(gh pr diff --name-only ${{ github.event.pull_request.number }})
        if [[ ! "$pr_files" =~ \.md$ ]]; then
          echo "PR is not related to documentation only. Exiting."
          exit 1
        fi

    - name: Merge Pull Request
      run: |
        pr_number=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)
        gh pr merge "$pr_number" --merge --auto --admin
