name: Auto Merge

on:
  pull_request:
  merge_group:

jobs:
  auto-merge:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        if: ${{ github.event_name == 'pull_request' && success() }}
        run: gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
