name: Auto Merge workflow

on:
  pull_request:
    branches: ['**']
  merge_group:
    branches: ['**']

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Wait for checks to pass
        run: |
          # Wait for status check rollup to show all checks are successful, excluding the current workflow check
          PR_STATUS=$(gh pr view ${{ github.event.pull_request.number }} --json statusCheckRollup -q '.statusCheckRollup | map(select(.app.slug != "github-actions")) | all(.conclusion == "SUCCESS")')
          
          while [[ "$PR_STATUS" != "true" ]]; do
            echo "Waiting for checks to pass..."
            sleep 10
            PR_STATUS=$(gh pr view ${{ github.event.pull_request.number }} --json statusCheckRollup -q '.statusCheckRollup | map(select(.app.slug != "github-actions")) | all(.conclusion == "SUCCESS")')
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        if: success()
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
