name: Auto Merge PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'trusted-user' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
