name: Auto Merge PRs

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [closed]

jobs:
  auto-merge:
    if: |
      (github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.pull_request.user.login == 'yachnytskyi') || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.user.login == 'yachnytskyi')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git configuration
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Merge PR after approval
      run: |
        TARGET_BRANCH="${{ github.base_ref }}"
        git fetch origin ${{ github.head_ref }}
        git checkout ${{ github.head_ref }}
        git merge origin/${TARGET_BRANCH} --no-ff --commit -m "Auto merge PR"
        git push origin HEAD:${TARGET_BRANCH}
