name: Auto Merge PR when checks pass

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '**'  # Trigger on any branch

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Wait for checks to pass
        run: |
          echo "Waiting for checks to pass..."
          PR_STATUS=$(gh pr view ${{ github.event.pull_request.number }} --json checksStatus -q ".checksStatus")
          while [[ "$PR_STATUS" != "success" ]]; do
            echo "Waiting for checks to complete..."
            sleep 10
            PR_STATUS=$(gh pr view ${{ github.event.pull_request.number }} --json checksStatus -q ".checksStatus")
          done
          
      - name: Merge PR
        if: success()
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
