name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - release
      - main
  pull_request:
    branches:
      - dev
      - release
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3' # Replace with your Go version

      # Step 3: Run Unit Tests for All Commits
      - name: Run Unit Tests
        run: make unit-tests

      # Step 4: Conditional Build and Testing for Merges
      - name: Build and Test Based on Branch
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "Building for dev branch"
            make tests
            make mongo-dev app-dev
          elif [[ "${{ github.ref_name }}" == "release" ]]; then
            echo "Building for release branch"
            make tests
            make mongo-release app-release
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Building for main (production) branch"
            make tests
            make mongo-production app-production
          else
            echo "Branch not recognized for build steps"
          fi
