name: Common Setup

on:
  workflow_call:  # This makes it reusable in other workflows

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      # Step 3: Run GolangCI-Lint to check code quality
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      # Step 4: Run unit tests
      - name: Run Unit Tests
        run: go test ./test/unit/...  # Adjust the test path if needed
