name: Develop workflow

on:
 # push:
    # branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Decode and Create YAML File
      run: |
        echo "${{ secrets.DOCKER_DEVELOP_APPLICATION_CONFIG_YAML }}" | base64 -d > config/yaml/v1/docker.develop.application.yaml

    - name: Create .env file for MongoDB
      run: |
        echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" > infrastructure/script/data/repository/mongo/.env
        echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> infrastructure/script/data/repository/mongo/.env
        echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> infrastructure/script/data/repository/mongo/.env

    - name: Build and Run Develop
      run: |
        docker compose up mongodb app-develop -d

    - name: Check MongoDB Logs
      run: docker logs mongodb
   
    - name: Wait for MongoDB to be Ready
      run: |
        for i in {1..10}; do
          docker exec mongodb mongodb --eval "db.runCommand({ping: 1})" && break || sleep 5
        done

    - name: Check App-Develop Logs
      run: |
        docker logs mongodb
        docker logs go-blog-platform-app-develop-1

    - name: List All Running Containers
      run: docker ps

    - name: Stop Develop
      run: docker stop $(docker ps -a -q)