name: Develop workflow

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Test
      run: go test -v ./...

    - name: Set up configuration files
      run: |
        # Use printf to correctly handle multi-line secrets and special characters
        printf "%s" "${{ secrets.DEVELOP_ENV_FILE }}" > ./config/environment/.develop.env
        printf "%s" "${{ secrets.DEVELOP_YAML_FILE }}" > ./config/yaml/v1/develop.application.yaml

    - name: Build and Run Develop Services
      run: docker compose up mongodb app-develop -d
