name: Develop workflow

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Decode and Decrypt YAML File
      run: |
        # Decode the Base64-encoded secret and decrypt it with OpenSSL
        echo "${{ secrets.DOCKER_DEVELOP_APPLICATION_CONFIG_YAML }}" | base64 -d > docker.develop.application.yaml.enc
        openssl enc -aes-256-cbc -d -in docker.develop.application.yaml.enc -out config/yaml/v1/docker.develop.application.yaml -pass pass:${{ secrets.ENCRYPTION_PASSWORD }}

    - name: Debug - Print YAML File Content
      run: |
        echo "Content of docker.develop.application.yaml:"
        cat config/yaml/v1/docker.develop.application.yaml

    - name: Build and Run Develop Services
      run: docker compose up mongodb app-develop -d