name: Develop workflow

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Decode and Create YAML File
      run: |
        echo "${{ secrets.DOCKER_DEVELOP_APPLICATION_CONFIG_YAML }}" | base64 -d > config/yaml/v1/docker.develop.application.yaml

    - name: Create .env file for MongoDB
      run: |
        echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" > infrastructure/script/data/repository/mongo/.env
        echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> infrastructure/script/data/repository/mongo/.env
        echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> infrastructure/script/data/repository/mongo/.env

    - name: Build and Run MongoDB
      run: |
        docker compose up -d mongodb
      
        # Optionally, check MongoDB health status directly:
        docker inspect --format='{{.State.Health.Status}}' mongodb

    - name: Build and Run Web Server (App)
      run: |
        docker compose up -d app-develop

    - name: Show MongoDB logs
      run: docker logs mongodb

    - name: Show App Logs
      run: |
        sleep 4  # Wait for 4 seconds to allow container to start up
        docker logs go-blog-platform-app-develop-1

    - name: List All Running Containers
      run: docker ps

    - name: Stop Develop
      run: docker stop $(docker ps -a -q)
