name: Develop workflow

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Decode and Create YAML File
      run: |
        echo "${{ secrets.DOCKER_DEVELOP_APPLICATION_CONFIG_YAML }}" | base64 -d > config/yaml/v1/docker.develop.application.yaml

    - name: Create .env file for MongoDB
      run: |
        echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" > infrastructure/script/data/repository/mongo/.env
        echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> infrastructure/script/data/repository/mongo/.env
        echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> infrastructure/script/data/repository/mongo/.env

    - name: Start MongoDB
      run: docker compose up mongodb -d

    - name: Wait for MongoDB to be Ready
      run: |
        for i in {1..10}; do
          nc -zv localhost 27017 && break || sleep 5
        done || exit 1

    - name: Start Application
      run: docker compose up app-develop -d

    - name: Check Application Logs
      sleep 7  # Wait for 7 seconds to allow container to start up
      run: docker logs go-blog-platform-app-develop-1

    - name: List All Running Containers
      run: docker ps

    - name: Stop All Containers
      run: docker stop $(docker ps -a -q)
