name: Develop workflow

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Test
      run: go test -v ./...

    - name: Create config directory
      run: |
        mkdir -p ./config/environment ./config/yaml/v1

    - name: Download config files from GitHub Secrets
      run: |
        echo "$DEVELOP_YAML_FILE" > ./config/yaml/v1/docker.develop.application.yaml

    - name: Build and Run Develop Services
      run: docker compose up mongodb app-develop -d
