name: Develop workflow

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Decode and Create YAML File
      run: |
        echo "${{ secrets.DOCKER_DEVELOP_APPLICATION_CONFIG_YAML }}" | base64 -d > config/yaml/v1/docker.develop.application.yaml

    - name: Create .env file for MongoDB
      run: |
        echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" > infrastructure/script/data/repository/mongo/.env
        echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> infrastructure/script/data/repository/mongo/.env
        echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> infrastructure/script/data/repository/mongo/.env

    - name: Build and Start Containers
      run: docker compose up mongodb -d

    - name: Wait for MongoDB to be ready
      run: |
        for i in {1..10}; do
          if docker inspect --format '{{json .State.Health.Status}}' mongodb | grep -q '"healthy"'; then
            echo "MongoDB is ready!"
            break
          fi
          echo "Waiting for MongoDB..."
          sleep 5
        done

    - name: Start Application
      run: docker compose up app-develop -d

    - name: Wait for Application to be ready
      run: |
        for i in {1..10}; do
          if docker inspect --format '{{json .State.Health.Status}}' app-develop | grep -q '"healthy"'; then
            echo "Application is ready!"
            break
          fi
          echo "Waiting for Application..."
          sleep 5
        done

    - name: Check Application Logs
      run: docker logs go-blog-platform-app-develop-1

    - name: List All Running Containers
      run: docker ps

    - name: Stop and Cleanup Containers
      run: docker stop $(docker ps -a -q)

