name: CI for Main (Production) Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go with the latest stable version
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      # Run unit tests for each commit (common step)
      - name: Run Unit Tests
        run: go test ./test/unit/...

      # Build and run Docker services for the main branch
      - name: Build and Run Production Services
        run: docker compose up mongodb app-production -d

      # Clean up Docker containers
      - name: Clean Up Docker
        run: docker compose down -v
