name: Main workflow

on:
  pull_request:
    branches: ['main']

jobs:
  setup:
    name: Set up environment and run lint/tests
    uses: ./.github/workflows/common-setup.yml

  production:
    name: Build and Run Production
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Decode and Create YAML File
      run: |
        echo "${{ secrets.DOCKER_PRODUCTION_APPLICATION_CONFIG_YAML }}" | base64 -d > config/yaml/v1/docker.production.application.yaml

    - name: Create .env file for MongoDB
      run: |
        echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" > infrastructure/script/data/repository/mongo/.env
        echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> infrastructure/script/data/repository/mongo/.env
        echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> infrastructure/script/data/repository/mongo/.env

    - name: Build and Run Production
      run: |
        docker compose up mongodb app-production -d
        sleep 7  # Wait for 7 seconds to allow containers to start up
        docker logs go-blog-platform-app-production-1

    - name: List All Running Containers
      run: docker ps

    - name: Stop Production
      run: docker stop $(docker ps -a -q)
