name: Production Services

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.3'

    - name: Build and Run Production Services
      run: docker compose up mongodb app-production -d
