name: Release (pre-Production) workflow

on:
  # push:
    # branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Decode and Create YAML File
      run: |
        echo "${{ secrets.DOCKER_RELEASE_APPLICATION_CONFIG_YAML }}" | base64 -d > config/yaml/v1/docker.release.application.yaml

    - name: Debug - Print YAML File Content
      run: |
        echo "Content of docker.release.application.yaml:"
        cat config/yaml/v1/docker.release.application.yaml

    - name: Build and Run Release
      run: docker compose up mongodb app-release -d