# .github/workflows/tag-version.yml
name: Tag Version Workflow

on:
  workflow_call:  # This makes it reusable
    inputs:
      version_override:
        description: 'Override version (optional)'
        required: false
        type: string

jobs:
  determine-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Determine Version Tag
      id: version
      run: |
        # Check if an override is provided, otherwise use the latest git tag
        if [ -n "${{ inputs.version_override }}" ]; then
          VERSION=${{ inputs.version_override }}
        else
          VERSION=$(git describe --tags --abbrev=0 || echo "1.0.0")
        fi
        
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version Tag: $VERSION"
