name: Determine Version Tag

on:
  workflow_call:  # This makes it reusable.

jobs:
  determine_version:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Version Tag
        id: version
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag -l --sort=-v:refname | head -n 1)

          if [ -z "$LATEST_TAG" ]; then
            VERSION="1.0.0"
          else
            VERSION="$LATEST_TAG"
          fi

          # Set the environment variable for the next steps
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version Tag: $VERSION"

